"""Add Amenity model

Revision ID: 464da66c4597
Revises: 1db36c385b2f
Create Date: 2023-06-08 16:20:33.483520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464da66c4597'
down_revision = '1db36c385b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amenity')
    # ### end Alembic commands ###
