"""empty message

Revision ID: e64241b12f00
Revises: 464da66c4597
Create Date: 2023-06-08 19:25:02.392145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e64241b12f00'
down_revision = '464da66c4597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_amenities',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['amenity_id'], ['amenity.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('hotel_id', 'amenity_id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=False))

    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('room_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_column('room_type')
        batch_op.drop_column('location')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')

    op.drop_table('room')
    op.drop_table('hotel_amenities')
    # ### end Alembic commands ###
